#!/usr/bin/env bash
#
# reconcile-package.sh — compute (and optionally act on) the desired state of
# one package's versioned docs.
#
# Policy:
#   - Blessed first-party providers keep their last HUGO_WINDOW majors in-Hugo
#     (generated by scripts/generate-versioned-docs.sh on every build); the
#     next-older major is served from the archive.
#   - Every other package keeps only the latest version in-Hugo; the last
#     ARCHIVE_DEPTH-1 older majors are served from the archive.
#   - Anything already archived stays archived (write-once; nothing here
#     deletes).
#
# The latest version is anchored on the package YAML's `version:` field (what
# the deployed site actually serves), not on the newest git tag — a provider may
# have tagged a release that hasn't been published to the registry yet.
#
# Output (stdout): a plan JSON —
#   {package, blessed, latest,
#    hugo_window: [<manifest entries with source:"hugo">],
#    archive:     [{version, slug, schema_url, published}],
#    skipped:     [{version, reason}]}
#
# The `archive` list is the work: entries with published=false need an
# archive-package-version run. With --bucket, `published` reflects the actual
# bucket contents; without it, every candidate is reported unpublished.
#
# --update-manifest additionally refreshes the manifest's hugo-window entries
# via publish-version.sh --manifest-only (needed even when nothing gets
# archived: a minor bump changes the latest version string in the dropdown).
#
# Usage:
#   reconcile-package.sh <package> [--bucket B] [--update-manifest]
#       [--distribution-id D] [--hugo-window-count 3] [--archive-depth 3]
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

for cmd in jq yq curl; do
    command -v "$cmd" >/dev/null || { echo "Missing dependency: $cmd" >&2; exit 1; }
done

# shellcheck source=scripts/versioned-docs/lib.sh
source "$SCRIPT_DIR/lib.sh"

PACKAGE="${1:-}"
[[ -n "$PACKAGE" ]] || { echo "usage: reconcile-package.sh <package> [flags]" >&2; exit 2; }
shift

BUCKET=""; UPDATE_MANIFEST="false"; DISTRIBUTION_ID=""
HUGO_WINDOW_COUNT=3   # majors kept in-Hugo for blessed packages
ARCHIVE_DEPTH=3       # total majors retained (in-Hugo + archive) at backfill time
while [[ $# -gt 0 ]]; do
    case "$1" in
        --bucket)            BUCKET="$2"; shift 2;;
        --update-manifest)   UPDATE_MANIFEST="true"; shift;;
        --distribution-id)   DISTRIBUTION_ID="$2"; shift 2;;
        --hugo-window-count) HUGO_WINDOW_COUNT="$2"; shift 2;;
        --archive-depth)     ARCHIVE_DEPTH="$2"; shift 2;;
        *) echo "reconcile-package: unknown arg: $1" >&2; exit 2;;
    esac
done

PACKAGE_YAML="$REPO_ROOT/themes/default/data/registry/packages/${PACKAGE}.yaml"
[[ -f "$PACKAGE_YAML" ]] || { echo "reconcile-package: package YAML not found: $PACKAGE_YAML" >&2; exit 1; }

LATEST_VERSION=$(yq '.version' "$PACKAGE_YAML")
[[ -n "$LATEST_VERSION" && "$LATEST_VERSION" != "null" ]] \
    || { echo "reconcile-package: no version in $PACKAGE_YAML" >&2; exit 1; }
[[ "$LATEST_VERSION" == v* ]] || LATEST_VERSION="v$LATEST_VERSION"

BLESSED="false"
if fetch_blessed_packages | grep -qx "$PACKAGE"; then
    BLESSED="true"
fi

# Blessed: the in-Hugo window plus one archive candidate (the major that left —
# or never entered — the window). Non-blessed: latest in-Hugo plus
# ARCHIVE_DEPTH-1 archive candidates.
if [[ "$BLESSED" == "true" ]]; then
    DISCOVER_COUNT=$((HUGO_WINDOW_COUNT + 1))
    WINDOW=$HUGO_WINDOW_COUNT
else
    DISCOVER_COUNT=$ARCHIVE_DEPTH
    WINDOW=1
fi

echo "reconcile-package: $PACKAGE blessed=$BLESSED latest=$LATEST_VERSION window=$WINDOW discover=$DISCOVER_COUNT" >&2
DISCOVERY=$("$SCRIPT_DIR/discover-versions.sh" "$PACKAGE" --major-count "$DISCOVER_COUNT" --minor-count 1)

# Partition discovered majors relative to the YAML latest:
#   major == latest major        -> covered by the latest in-Hugo entry
#   next (WINDOW-1) lower majors -> in-Hugo (blessed only)
#   remaining lower majors       -> archive candidates
# Majors *above* the YAML latest (tagged but not yet published) are ignored.
PLAN=$(printf '%s' "$DISCOVERY" | jq \
    --arg pkg "$PACKAGE" --arg latest "$LATEST_VERSION" \
    --argjson window "$WINDOW" --arg blessed "$BLESSED" '
    ( $latest | ltrimstr("v") | split(".")[0] | tonumber ) as $latestMajor
    | ( .versions // []
        | map(. + { major: (.version | split(".")[0] | tonumber) })
        | map(select(.major <= $latestMajor))
        | sort_by(-.major) ) as $discovered
    | ( $discovered | map(select(.major < $latestMajor)) ) as $older
    | ( $older[0:($window - 1)] ) as $hugoOlder
    | ( $older[($window - 1):] ) as $archive
    | {
        package: $pkg,
        blessed: ($blessed == "true"),
        latest: $latest,
        hugo_window: (
          [ { version: $latest, slug: "", path: ("/registry/packages/" + $pkg + "/"), latest: true, source: "hugo" } ]
          + ( $hugoOlder | map({
                version: ("v" + .version),
                slug: ((.major | tostring) + ".x"),
                path: ("/registry/packages/" + $pkg + "@" + (.major | tostring) + ".x/"),
                source: "hugo"
              }) )
        ),
        archive: ( $archive | map({
            version: ("v" + .version),
            slug: ((.major | tostring) + ".x"),
            schema_url: .schema_url,
            published: false
          }) ),
        skipped: (.skipped // [])
      }
')

# Mark archive candidates that already exist in the bucket.
if [[ -n "$BUCKET" ]]; then
    while read -r slug; do
        [[ -n "$slug" ]] || continue
        prefix="registry/packages/${PACKAGE}@${slug}/"
        count="$(aws s3api list-objects-v2 --bucket "$BUCKET" --prefix "$prefix" --max-items 1 \
            --query 'length(Contents || `[]`)' --output text 2>/dev/null || echo 0)"
        if [[ "$count" != "0" && "$count" != "None" ]]; then
            PLAN=$(printf '%s' "$PLAN" | jq --arg slug "$slug" \
                '.archive = (.archive | map(if .slug == $slug then .published = true else . end))')
        fi
    done < <(printf '%s' "$PLAN" | jq -r '.archive[].slug')
fi

if [[ "$UPDATE_MANIFEST" == "true" ]]; then
    [[ -n "$BUCKET" ]] || { echo "reconcile-package: --update-manifest requires --bucket" >&2; exit 2; }
    HUGO_WINDOW_JSON=$(printf '%s' "$PLAN" | jq -c '.hugo_window')
    manifest_args=(--package "$PACKAGE" --manifest-only --hugo-window "$HUGO_WINDOW_JSON" --bucket "$BUCKET")
    [[ -n "$DISTRIBUTION_ID" ]] && manifest_args+=(--distribution-id "$DISTRIBUTION_ID")
    "$SCRIPT_DIR/publish-version.sh" "${manifest_args[@]}" >&2
fi

printf '%s\n' "$PLAN"
