// Copyright 2024, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package pkg

var CategoryNameMap = map[string]PackageCategory{
	"cloud":          PackageCategoryCloud,
	"database":       PackageCategoryDatabase,
	"infrastructure": PackageCategoryInfrastructure,
	"monitoring":     PackageCategoryMonitoring,
	"network":        PackageCategoryNetwork,
	"utility":        PackageCategoryUtility,
	"vcs":            PackageCategoryVCS,
}

var CategoryLookup = map[string]PackageCategory{
	"aiven":                               PackageCategoryInfrastructure,
	"akamai":                              PackageCategoryNetwork,
	"alicloud":                            PackageCategoryCloud,
	"auth0":                               PackageCategoryInfrastructure,
	"aws":                                 PackageCategoryCloud,
	"aws-apigateway":                      PackageCategoryCloud,
	"aws-miniflux":                        PackageCategoryCloud,
	"aws-native":                          PackageCategoryCloud,
	"aws-quickstart-aurora-mysql":         PackageCategoryCloud,
	"aws-quickstart-aurora-postgresql":    PackageCategoryCloud,
	"aws-quickstart-redshift":             PackageCategoryCloud,
	"aws-serverless":                      PackageCategoryCloud,
	"aws-quickstart-vpc":                  PackageCategoryCloud,
	"aws-s3-replicated-bucket":            PackageCategoryCloud,
	"azure":                               PackageCategoryCloud,
	"azure-native":                        PackageCategoryCloud,
	"azure-quickstart-acr-geo-replicated": PackageCategoryCloud,
	"azure-quickstart-aks":                PackageCategoryCloud,
	"azure-quickstart-compute":            PackageCategoryCloud,
	"azure-quickstart-sql":                PackageCategoryCloud,
	"azuread":                             PackageCategoryInfrastructure,
	"azuredevops":                         PackageCategoryInfrastructure,
	"civo":                                PackageCategoryCloud,
	"cloudamqp":                           PackageCategoryCloud,
	"cloudflare":                          PackageCategoryNetwork,
	"cloudinit":                           PackageCategoryUtility,
	"confluent":                           PackageCategoryInfrastructure,
	"consul":                              PackageCategoryInfrastructure,
	"coredns-helm":                        PackageCategoryNetwork,
	"datadog":                             PackageCategoryMonitoring,
	"digitalocean":                        PackageCategoryCloud,
	"dnsimple":                            PackageCategoryNetwork,
	"docker":                              PackageCategoryInfrastructure,
	"docker-buildkit":                     PackageCategoryInfrastructure,
	"eks":                                 PackageCategoryCloud,
	"equinix-metal":                       PackageCategoryCloud,
	"f5bigip":                             PackageCategoryNetwork,
	"fastly":                              PackageCategoryCloud,
	"gcp":                                 PackageCategoryCloud,
	"gcp-cloudrun-multi-region":           PackageCategoryCloud,
	"gcp-project-scaffold":                PackageCategoryCloud,
	"google-native":                       PackageCategoryCloud,
	"github":                              PackageCategoryVCS,
	"github-serverless-webhook":           PackageCategoryVCS,
	"gitlab":                              PackageCategoryVCS,
	"hcloud":                              PackageCategoryCloud,
	"istio-helm":                          PackageCategoryInfrastructure,
	"jaeger-helm":                         PackageCategoryMonitoring,
	"kafka":                               PackageCategoryInfrastructure,
	"keycloak":                            PackageCategoryInfrastructure,
	"kong":                                PackageCategoryInfrastructure,
	"kubernetes":                          PackageCategoryCloud,
	"libvirt":                             PackageCategoryUtility,
	"linode":                              PackageCategoryCloud,
	"mailgun":                             PackageCategoryInfrastructure,
	"minio":                               PackageCategoryInfrastructure,
	"mongodbatlas":                        PackageCategoryDatabase,
	"mysql":                               PackageCategoryDatabase,
	"newrelic":                            PackageCategoryMonitoring,
	"nginx-ingress-controller-helm":       PackageCategoryNetwork,
	"nomad":                               PackageCategoryInfrastructure,
	"ns1":                                 PackageCategoryNetwork,
	"okta":                                PackageCategoryInfrastructure,
	"onelogin":                            PackageCategoryInfrastructure,
	"openstack":                           PackageCategoryCloud,
	"opsgenie":                            PackageCategoryInfrastructure,
	"pagerduty":                           PackageCategoryInfrastructure,
	"pgedge":                              PackageCategoryDatabase,
	"postgresql":                          PackageCategoryDatabase,
	"prometheus-helm":                     PackageCategoryMonitoring,
	"rabbitmq":                            PackageCategoryInfrastructure,
	"rancher2":                            PackageCategoryInfrastructure,
	"random":                              PackageCategoryUtility,
	"rke":                                 PackageCategoryInfrastructure,
	"shipa":                               PackageCategoryCloud,
	"signalfx":                            PackageCategoryMonitoring,
	"snowflake":                           PackageCategoryInfrastructure,
	"splunk":                              PackageCategoryInfrastructure,
	"spotinst":                            PackageCategoryInfrastructure,
	"sumologic":                           PackageCategoryMonitoring,
	"tls":                                 PackageCategoryUtility,
	"vault":                               PackageCategoryInfrastructure,
	"venafi":                              PackageCategoryInfrastructure,
	"vsphere":                             PackageCategoryCloud,
	"wavefront":                           PackageCategoryMonitoring,
	"yandex":                              PackageCategoryCloud,
}

// TODO[pulumi/pulumi#7813]: Remove this lookup once display name is available in
// the Pulumi schema.
//
// NOTE: For the time being this lookup map and the one used by the docs
// generator in `pulumi/pulumi` must be kept up-to-date.
//
// titleLookup is a map pf package name to the desired display name
// for display in the TOC menu under API Reference.
var TitleLookup = map[string]string{
	"aiven":                               "Aiven",
	"akamai":                              "Akamai",
	"alicloud":                            "Alibaba Cloud",
	"auth0":                               "Auth0",
	"aws":                                 "AWS",
	"aws-apigateway":                      "AWS API Gateway",
	"aws-miniflux":                        "Miniflux",
	"aws-native":                          "AWS Cloud Control",
	"aws-quickstart-aurora-mysql":         "AWS QuickStart Aurora MySQL",
	"aws-quickstart-aurora-postgresql":    "AWS QuickStart Aurora PostgreSQL",
	"aws-quickstart-redshift":             "AWS QuickStart Redshift",
	"aws-serverless":                      "AWS Serverless",
	"aws-quickstart-vpc":                  "AWS QuickStart VPC",
	"aws-s3-replicated-bucket":            "AWS S3 Replicated Bucket",
	"azure":                               "Azure Classic",
	"azure-native":                        "Azure Native",
	"azure-quickstart-acr-geo-replicated": "Azure QuickStart ACR Geo Replicated",
	"azure-quickstart-aks":                "Azure QuickStart AKS",
	"azure-quickstart-compute":            "Azure QuickStart Compute",
	"azure-quickstart-sql":                "Azure QuickStart SQL",
	"azuread":                             "Azure Active Directory",
	"azuredevops":                         "Azure DevOps",
	"azuresel":                            "Azure",
	"civo":                                "Civo",
	"cloudamqp":                           "CloudAMQP",
	"cloudflare":                          "Cloudflare",
	"cloudinit":                           "cloud-init",
	"confluent":                           "Confluent Cloud",
	"consul":                              "Consul",
	"coredns-helm":                        "CoreDNS (Helm)",
	"datadog":                             "Datadog",
	"digitalocean":                        "DigitalOcean",
	"dnsimple":                            "DNSimple",
	"docker":                              "Docker",
	"docker-buildkit":                     "Docker BuildKit",
	"eks":                                 "Amazon EKS",
	"equinix-metal":                       "Equinix Metal",
	"f5bigip":                             "f5 BIG-IP",
	"fastly":                              "Fastly",
	"gcp":                                 "Google Cloud Classic",
	"gcp-cloudrun-multi-region":           "Google Cloud Run Multi-Region",
	"gcp-project-scaffold":                "Google Project Scaffolding",
	"google-native":                       "Google Cloud Native",
	"github":                              "GitHub",
	"github-serverless-webhook":           "GitHub Serverless Webhook",
	"gitlab":                              "GitLab",
	"hcloud":                              "Hetzner Cloud",
	"istio-helm":                          "Istio (Helm)",
	"jaeger-helm":                         "Jaeger (Helm)",
	"kafka":                               "Kafka",
	"keycloak":                            "Keycloak",
	"kong":                                "Kong",
	"kubernetes":                          "Kubernetes",
	"libvirt":                             "libvirt",
	"linode":                              "Linode",
	"mailgun":                             "Mailgun",
	"minio":                               "MinIO",
	"mongodbatlas":                        "MongoDB Atlas",
	"mysql":                               "MySQL",
	"newrelic":                            "New Relic",
	"nginx-ingress-controller-helm":       "NGINX Ingress Controller (Helm)",
	"nomad":                               "Nomad",
	"ns1":                                 "NS1",
	"okta":                                "Okta",
	"openstack":                           "OpenStack",
	"opsgenie":                            "Opsgenie",
	"packet":                              "Packet",
	"pagerduty":                           "PagerDuty",
	"pgedge":                              "pgEdge",
	"postgresql":                          "PostgreSQL",
	"prometheus-helm":                     "Prometheus (Helm)",
	"rabbitmq":                            "RabbitMQ",
	"rancher2":                            "Rancher 2",
	"random":                              "random",
	"rke":                                 "Rancher RKE",
	"shipa":                               "Shipa",
	"signalfx":                            "SignalFx",
	"snowflake":                           "Snowflake",
	"splunk":                              "Splunk",
	"spotinst":                            "Spotinst",
	"sumologic":                           "Sumo Logic",
	"tls":                                 "TLS",
	"vault":                               "Vault",
	"venafi":                              "Venafi",
	"vsphere":                             "vSphere",
	"wavefront":                           "Wavefront",
	"yandex":                              "Yandex",
}
