/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { APINavNode } from "./components/pulumi-api-doc-filterable-nav/pulumi-api-doc-filterable-nav";
import { ChooserKey, ChooserMode, ChooserType } from "./components/chooser/chooser";
import { ChooserKey as ChooserKey1, ChooserMode as ChooserMode1, ChooserOptionStyle, ChooserType as ChooserType1 } from "./components/chooser/chooser";
import { SourceKind } from "./components/convert/convert";
import { Filter } from "./components/filter-select/filter-select-option";
import { MultiSelectFormItem } from "./components/pulumi-multi-select-form/pulumi-multi-select-form";
export { APINavNode } from "./components/pulumi-api-doc-filterable-nav/pulumi-api-doc-filterable-nav";
export { ChooserKey, ChooserMode, ChooserType } from "./components/chooser/chooser";
export { ChooserKey as ChooserKey1, ChooserMode as ChooserMode1, ChooserOptionStyle, ChooserType as ChooserType1 } from "./components/chooser/chooser";
export { SourceKind } from "./components/convert/convert";
export { Filter } from "./components/filter-select/filter-select-option";
export { MultiSelectFormItem } from "./components/pulumi-multi-select-form/pulumi-multi-select-form";
export namespace Components {
    interface PulumiApiDocFilterableNav {
        "baseDirectory": string;
        "packageName": string;
    }
    interface PulumiApiDocNavNode {
        /**
          * @default 0
         */
        "depth": number;
        "href": string;
        "isExpanded": boolean;
        "node": APINavNode;
    }
    interface PulumiApiDocNavTree {
        "baseDirectory": string;
        "nodes": APINavNode[];
    }
    /**
     * The Choosable component is useful for showing or hiding information based on the
     * currently selected ChooserType and value. For example, a component defined as:
     *     <pulumi-choosable type="language" value="typescript">
     *         I <3 TypeScript.
     *     </pulumi-choosable>
     * ...would display "I <3 TypeScript" only when the user's currently (or most recently)
     * selected language choice is TypeScript.
     */
    interface PulumiChoosable {
        "mode": ChooserMode;
        "selection": ChooserKey;
        "type": ChooserType;
        "value": ChooserKey;
        "values": ChooserKey;
    }
    /**
     * The Chooser component renders a set of selectable tabs based on the type and options
     * properties provided. For example, this definition:
     *     <pulumi-chooser type="language" value="typescript,python,go"></pulumi-chooser>
     * ...would render three tabs. Clicking a tab dispatches an action that sets the
     * associated value on the store, allowing any pulumi-choosable component on the page to
     * be shown or hidden automatically.
     * Alternatively, you can provide one or more pulumi-choosable components as children of
     * this component, which will have the effect of treating them as tabbed content,
     * irrespective of what may or may not be set on the global store. For example:
     *     <pulumi-chooser type="language" value="typescript,javascript">
     *         <pulumi choosable type="language" value="typescript">Some TypeScript</pulumi-choosable>
     *         <pulumi choosable type="language" value="javascript">Some JavaScript</pulumi-choosable>
     *     </pulumi-chooser>
     */
    interface PulumiChooser {
        "mode": ChooserMode1;
        "optionStyle": ChooserOptionStyle;
        "options": string;
        "selection": ChooserKey1;
        "type": ChooserType1;
    }
    interface PulumiContactUsForm {
        "items": string;
        "labelClass"?: string;
        "selectClass"?: string;
    }
    interface PulumiConvert {
        "endpoint": string;
        "examples": string;
        "from": SourceKind;
        /**
          * @default ""
         */
        "theme": string;
    }
    interface PulumiExample {
    }
    interface PulumiExamples {
    }
    interface PulumiFilterSelect {
        "deselect": (filter: Filter) => Promise<void>;
        "reset": () => Promise<any>;
        "select": (filter: Filter) => Promise<void>;
    }
    interface PulumiFilterSelectOption {
        "deselect": () => Promise<void>;
        "label"?: string;
        "select": () => Promise<void>;
        "selected": boolean;
        "value": string;
    }
    interface PulumiFilterSelectOptionGroup {
        "close": () => Promise<any>;
        "expanded": boolean;
        "name": string;
    }
    interface PulumiHubspotForm {
        "class"?: string;
        "formId": string;
        "goToWebinarKey"?: string;
        "salesforceCampaignId": string;
    }
    interface PulumiMultiSelectForm {
        /**
          * @default ""
         */
        "defaultFormId": string;
        /**
          * @default []
         */
        "items": MultiSelectFormItem[];
        "labelClass"?: string;
        "labelText": string;
        "selectClass"?: string;
    }
    interface PulumiRegistryListSearch {
    }
    interface PulumiResourceLinks {
        "moduleName": string;
        "packageName": string;
        "resourceName": string;
    }
    interface PulumiRoot {
    }
    /**
     * The ToolTip component shows a tooltip bubble above another element when you hover over
     * (or, on mobile tap on) it. Use the named `content` slot for supplying the markup to
     * show in the bubble.
     * Usage:
     * <pulumi-tooltip>
     *     <i class="fas fa-question-circle"></i>
     *     <span slot="content">
     *         You hovered over (or tapped on) the thing!
     *     </span>
     * </pulumi-tooltip>
     */
    interface PulumiTooltip {
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
    }
    interface PulumiTopButton {
    }
    interface PulumiUserToggle {
        "userId": string;
    }
}
export interface PulumiFilterSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPulumiFilterSelectElement;
}
export interface PulumiFilterSelectOptionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPulumiFilterSelectOptionElement;
}
export interface PulumiRegistryListSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPulumiRegistryListSearchElement;
}
export interface PulumiRootCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPulumiRootElement;
}
declare global {
    interface HTMLPulumiApiDocFilterableNavElement extends Components.PulumiApiDocFilterableNav, HTMLStencilElement {
    }
    var HTMLPulumiApiDocFilterableNavElement: {
        prototype: HTMLPulumiApiDocFilterableNavElement;
        new (): HTMLPulumiApiDocFilterableNavElement;
    };
    interface HTMLPulumiApiDocNavNodeElement extends Components.PulumiApiDocNavNode, HTMLStencilElement {
    }
    var HTMLPulumiApiDocNavNodeElement: {
        prototype: HTMLPulumiApiDocNavNodeElement;
        new (): HTMLPulumiApiDocNavNodeElement;
    };
    interface HTMLPulumiApiDocNavTreeElement extends Components.PulumiApiDocNavTree, HTMLStencilElement {
    }
    var HTMLPulumiApiDocNavTreeElement: {
        prototype: HTMLPulumiApiDocNavTreeElement;
        new (): HTMLPulumiApiDocNavTreeElement;
    };
    /**
     * The Choosable component is useful for showing or hiding information based on the
     * currently selected ChooserType and value. For example, a component defined as:
     *     <pulumi-choosable type="language" value="typescript">
     *         I <3 TypeScript.
     *     </pulumi-choosable>
     * ...would display "I <3 TypeScript" only when the user's currently (or most recently)
     * selected language choice is TypeScript.
     */
    interface HTMLPulumiChoosableElement extends Components.PulumiChoosable, HTMLStencilElement {
    }
    var HTMLPulumiChoosableElement: {
        prototype: HTMLPulumiChoosableElement;
        new (): HTMLPulumiChoosableElement;
    };
    /**
     * The Chooser component renders a set of selectable tabs based on the type and options
     * properties provided. For example, this definition:
     *     <pulumi-chooser type="language" value="typescript,python,go"></pulumi-chooser>
     * ...would render three tabs. Clicking a tab dispatches an action that sets the
     * associated value on the store, allowing any pulumi-choosable component on the page to
     * be shown or hidden automatically.
     * Alternatively, you can provide one or more pulumi-choosable components as children of
     * this component, which will have the effect of treating them as tabbed content,
     * irrespective of what may or may not be set on the global store. For example:
     *     <pulumi-chooser type="language" value="typescript,javascript">
     *         <pulumi choosable type="language" value="typescript">Some TypeScript</pulumi-choosable>
     *         <pulumi choosable type="language" value="javascript">Some JavaScript</pulumi-choosable>
     *     </pulumi-chooser>
     */
    interface HTMLPulumiChooserElement extends Components.PulumiChooser, HTMLStencilElement {
    }
    var HTMLPulumiChooserElement: {
        prototype: HTMLPulumiChooserElement;
        new (): HTMLPulumiChooserElement;
    };
    interface HTMLPulumiContactUsFormElement extends Components.PulumiContactUsForm, HTMLStencilElement {
    }
    var HTMLPulumiContactUsFormElement: {
        prototype: HTMLPulumiContactUsFormElement;
        new (): HTMLPulumiContactUsFormElement;
    };
    interface HTMLPulumiConvertElement extends Components.PulumiConvert, HTMLStencilElement {
    }
    var HTMLPulumiConvertElement: {
        prototype: HTMLPulumiConvertElement;
        new (): HTMLPulumiConvertElement;
    };
    interface HTMLPulumiExampleElement extends Components.PulumiExample, HTMLStencilElement {
    }
    var HTMLPulumiExampleElement: {
        prototype: HTMLPulumiExampleElement;
        new (): HTMLPulumiExampleElement;
    };
    interface HTMLPulumiExamplesElement extends Components.PulumiExamples, HTMLStencilElement {
    }
    var HTMLPulumiExamplesElement: {
        prototype: HTMLPulumiExamplesElement;
        new (): HTMLPulumiExamplesElement;
    };
    interface HTMLPulumiFilterSelectElementEventMap {
        "filterSelect": any[];
    }
    interface HTMLPulumiFilterSelectElement extends Components.PulumiFilterSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPulumiFilterSelectElementEventMap>(type: K, listener: (this: HTMLPulumiFilterSelectElement, ev: PulumiFilterSelectCustomEvent<HTMLPulumiFilterSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPulumiFilterSelectElementEventMap>(type: K, listener: (this: HTMLPulumiFilterSelectElement, ev: PulumiFilterSelectCustomEvent<HTMLPulumiFilterSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPulumiFilterSelectElement: {
        prototype: HTMLPulumiFilterSelectElement;
        new (): HTMLPulumiFilterSelectElement;
    };
    interface HTMLPulumiFilterSelectOptionElementEventMap {
        "optionChange": any;
    }
    interface HTMLPulumiFilterSelectOptionElement extends Components.PulumiFilterSelectOption, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPulumiFilterSelectOptionElementEventMap>(type: K, listener: (this: HTMLPulumiFilterSelectOptionElement, ev: PulumiFilterSelectOptionCustomEvent<HTMLPulumiFilterSelectOptionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPulumiFilterSelectOptionElementEventMap>(type: K, listener: (this: HTMLPulumiFilterSelectOptionElement, ev: PulumiFilterSelectOptionCustomEvent<HTMLPulumiFilterSelectOptionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPulumiFilterSelectOptionElement: {
        prototype: HTMLPulumiFilterSelectOptionElement;
        new (): HTMLPulumiFilterSelectOptionElement;
    };
    interface HTMLPulumiFilterSelectOptionGroupElement extends Components.PulumiFilterSelectOptionGroup, HTMLStencilElement {
    }
    var HTMLPulumiFilterSelectOptionGroupElement: {
        prototype: HTMLPulumiFilterSelectOptionGroupElement;
        new (): HTMLPulumiFilterSelectOptionGroupElement;
    };
    interface HTMLPulumiHubspotFormElement extends Components.PulumiHubspotForm, HTMLStencilElement {
    }
    var HTMLPulumiHubspotFormElement: {
        prototype: HTMLPulumiHubspotFormElement;
        new (): HTMLPulumiHubspotFormElement;
    };
    interface HTMLPulumiMultiSelectFormElement extends Components.PulumiMultiSelectForm, HTMLStencilElement {
    }
    var HTMLPulumiMultiSelectFormElement: {
        prototype: HTMLPulumiMultiSelectFormElement;
        new (): HTMLPulumiMultiSelectFormElement;
    };
    interface HTMLPulumiRegistryListSearchElementEventMap {
        "packageSearch": string;
    }
    interface HTMLPulumiRegistryListSearchElement extends Components.PulumiRegistryListSearch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPulumiRegistryListSearchElementEventMap>(type: K, listener: (this: HTMLPulumiRegistryListSearchElement, ev: PulumiRegistryListSearchCustomEvent<HTMLPulumiRegistryListSearchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPulumiRegistryListSearchElementEventMap>(type: K, listener: (this: HTMLPulumiRegistryListSearchElement, ev: PulumiRegistryListSearchCustomEvent<HTMLPulumiRegistryListSearchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPulumiRegistryListSearchElement: {
        prototype: HTMLPulumiRegistryListSearchElement;
        new (): HTMLPulumiRegistryListSearchElement;
    };
    interface HTMLPulumiResourceLinksElement extends Components.PulumiResourceLinks, HTMLStencilElement {
    }
    var HTMLPulumiResourceLinksElement: {
        prototype: HTMLPulumiResourceLinksElement;
        new (): HTMLPulumiResourceLinksElement;
    };
    interface HTMLPulumiRootElementEventMap {
        "rendered": any;
    }
    interface HTMLPulumiRootElement extends Components.PulumiRoot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPulumiRootElementEventMap>(type: K, listener: (this: HTMLPulumiRootElement, ev: PulumiRootCustomEvent<HTMLPulumiRootElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPulumiRootElementEventMap>(type: K, listener: (this: HTMLPulumiRootElement, ev: PulumiRootCustomEvent<HTMLPulumiRootElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPulumiRootElement: {
        prototype: HTMLPulumiRootElement;
        new (): HTMLPulumiRootElement;
    };
    /**
     * The ToolTip component shows a tooltip bubble above another element when you hover over
     * (or, on mobile tap on) it. Use the named `content` slot for supplying the markup to
     * show in the bubble.
     * Usage:
     * <pulumi-tooltip>
     *     <i class="fas fa-question-circle"></i>
     *     <span slot="content">
     *         You hovered over (or tapped on) the thing!
     *     </span>
     * </pulumi-tooltip>
     */
    interface HTMLPulumiTooltipElement extends Components.PulumiTooltip, HTMLStencilElement {
    }
    var HTMLPulumiTooltipElement: {
        prototype: HTMLPulumiTooltipElement;
        new (): HTMLPulumiTooltipElement;
    };
    interface HTMLPulumiTopButtonElement extends Components.PulumiTopButton, HTMLStencilElement {
    }
    var HTMLPulumiTopButtonElement: {
        prototype: HTMLPulumiTopButtonElement;
        new (): HTMLPulumiTopButtonElement;
    };
    interface HTMLPulumiUserToggleElement extends Components.PulumiUserToggle, HTMLStencilElement {
    }
    var HTMLPulumiUserToggleElement: {
        prototype: HTMLPulumiUserToggleElement;
        new (): HTMLPulumiUserToggleElement;
    };
    interface HTMLElementTagNameMap {
        "pulumi-api-doc-filterable-nav": HTMLPulumiApiDocFilterableNavElement;
        "pulumi-api-doc-nav-node": HTMLPulumiApiDocNavNodeElement;
        "pulumi-api-doc-nav-tree": HTMLPulumiApiDocNavTreeElement;
        "pulumi-choosable": HTMLPulumiChoosableElement;
        "pulumi-chooser": HTMLPulumiChooserElement;
        "pulumi-contact-us-form": HTMLPulumiContactUsFormElement;
        "pulumi-convert": HTMLPulumiConvertElement;
        "pulumi-example": HTMLPulumiExampleElement;
        "pulumi-examples": HTMLPulumiExamplesElement;
        "pulumi-filter-select": HTMLPulumiFilterSelectElement;
        "pulumi-filter-select-option": HTMLPulumiFilterSelectOptionElement;
        "pulumi-filter-select-option-group": HTMLPulumiFilterSelectOptionGroupElement;
        "pulumi-hubspot-form": HTMLPulumiHubspotFormElement;
        "pulumi-multi-select-form": HTMLPulumiMultiSelectFormElement;
        "pulumi-registry-list-search": HTMLPulumiRegistryListSearchElement;
        "pulumi-resource-links": HTMLPulumiResourceLinksElement;
        "pulumi-root": HTMLPulumiRootElement;
        "pulumi-tooltip": HTMLPulumiTooltipElement;
        "pulumi-top-button": HTMLPulumiTopButtonElement;
        "pulumi-user-toggle": HTMLPulumiUserToggleElement;
    }
}
declare namespace LocalJSX {
    interface PulumiApiDocFilterableNav {
        "baseDirectory"?: string;
        "packageName"?: string;
    }
    interface PulumiApiDocNavNode {
        /**
          * @default 0
         */
        "depth"?: number;
        "href"?: string;
        "isExpanded"?: boolean;
        "node"?: APINavNode;
    }
    interface PulumiApiDocNavTree {
        "baseDirectory"?: string;
        "nodes"?: APINavNode[];
    }
    /**
     * The Choosable component is useful for showing or hiding information based on the
     * currently selected ChooserType and value. For example, a component defined as:
     *     <pulumi-choosable type="language" value="typescript">
     *         I <3 TypeScript.
     *     </pulumi-choosable>
     * ...would display "I <3 TypeScript" only when the user's currently (or most recently)
     * selected language choice is TypeScript.
     */
    interface PulumiChoosable {
        "mode"?: ChooserMode;
        "selection"?: ChooserKey;
        "type"?: ChooserType;
        "value"?: ChooserKey;
        "values"?: ChooserKey;
    }
    /**
     * The Chooser component renders a set of selectable tabs based on the type and options
     * properties provided. For example, this definition:
     *     <pulumi-chooser type="language" value="typescript,python,go"></pulumi-chooser>
     * ...would render three tabs. Clicking a tab dispatches an action that sets the
     * associated value on the store, allowing any pulumi-choosable component on the page to
     * be shown or hidden automatically.
     * Alternatively, you can provide one or more pulumi-choosable components as children of
     * this component, which will have the effect of treating them as tabbed content,
     * irrespective of what may or may not be set on the global store. For example:
     *     <pulumi-chooser type="language" value="typescript,javascript">
     *         <pulumi choosable type="language" value="typescript">Some TypeScript</pulumi-choosable>
     *         <pulumi choosable type="language" value="javascript">Some JavaScript</pulumi-choosable>
     *     </pulumi-chooser>
     */
    interface PulumiChooser {
        "mode"?: ChooserMode1;
        "optionStyle"?: ChooserOptionStyle;
        "options"?: string;
        "selection"?: ChooserKey1;
        "type"?: ChooserType1;
    }
    interface PulumiContactUsForm {
        "items"?: string;
        "labelClass"?: string;
        "selectClass"?: string;
    }
    interface PulumiConvert {
        "endpoint"?: string;
        "examples"?: string;
        "from"?: SourceKind;
        /**
          * @default ""
         */
        "theme"?: string;
    }
    interface PulumiExample {
    }
    interface PulumiExamples {
    }
    interface PulumiFilterSelect {
        "onFilterSelect"?: (event: PulumiFilterSelectCustomEvent<any[]>) => void;
    }
    interface PulumiFilterSelectOption {
        "label"?: string;
        "onOptionChange"?: (event: PulumiFilterSelectOptionCustomEvent<any>) => void;
        "selected"?: boolean;
        "value"?: string;
    }
    interface PulumiFilterSelectOptionGroup {
        "expanded"?: boolean;
        "name"?: string;
    }
    interface PulumiHubspotForm {
        "class"?: string;
        "formId"?: string;
        "goToWebinarKey"?: string;
        "salesforceCampaignId"?: string;
    }
    interface PulumiMultiSelectForm {
        /**
          * @default ""
         */
        "defaultFormId"?: string;
        /**
          * @default []
         */
        "items"?: MultiSelectFormItem[];
        "labelClass"?: string;
        "labelText"?: string;
        "selectClass"?: string;
    }
    interface PulumiRegistryListSearch {
        "onPackageSearch"?: (event: PulumiRegistryListSearchCustomEvent<string>) => void;
    }
    interface PulumiResourceLinks {
        "moduleName"?: string;
        "packageName"?: string;
        "resourceName"?: string;
    }
    interface PulumiRoot {
        "onRendered"?: (event: PulumiRootCustomEvent<any>) => void;
    }
    /**
     * The ToolTip component shows a tooltip bubble above another element when you hover over
     * (or, on mobile tap on) it. Use the named `content` slot for supplying the markup to
     * show in the bubble.
     * Usage:
     * <pulumi-tooltip>
     *     <i class="fas fa-question-circle"></i>
     *     <span slot="content">
     *         You hovered over (or tapped on) the thing!
     *     </span>
     * </pulumi-tooltip>
     */
    interface PulumiTooltip {
    }
    interface PulumiTopButton {
    }
    interface PulumiUserToggle {
        "userId"?: string;
    }

    interface PulumiApiDocFilterableNavAttributes {
        "baseDirectory": string;
        "packageName": string;
    }
    interface PulumiApiDocNavNodeAttributes {
        "href": string;
        "depth": number;
        "isExpanded": boolean;
    }
    interface PulumiApiDocNavTreeAttributes {
        "baseDirectory": string;
    }
    interface PulumiChoosableAttributes {
        "type": ChooserType;
        "value": ChooserKey;
        "values": ChooserKey;
        "mode": ChooserMode;
        "selection": ChooserKey;
    }
    interface PulumiChooserAttributes {
        "type": ChooserType;
        "options": string;
        "selection": ChooserKey;
        "optionStyle": ChooserOptionStyle;
        "mode": ChooserMode;
    }
    interface PulumiContactUsFormAttributes {
        "items": string;
        "selectClass": string;
        "labelClass": string;
    }
    interface PulumiConvertAttributes {
        "from": SourceKind;
        "endpoint": string;
        "examples": string;
        "theme": string;
    }
    interface PulumiFilterSelectOptionAttributes {
        "label": string;
        "value": string;
        "selected": boolean;
    }
    interface PulumiFilterSelectOptionGroupAttributes {
        "name": string;
        "expanded": boolean;
    }
    interface PulumiHubspotFormAttributes {
        "formId": string;
        "salesforceCampaignId": string;
        "goToWebinarKey": string;
        "class": string;
    }
    interface PulumiMultiSelectFormAttributes {
        "selectClass": string;
        "labelClass": string;
        "labelText": string;
        "defaultFormId": string;
    }
    interface PulumiResourceLinksAttributes {
        "packageName": string;
        "moduleName": string;
        "resourceName": string;
    }
    interface PulumiUserToggleAttributes {
        "userId": string;
    }

    interface IntrinsicElements {
        "pulumi-api-doc-filterable-nav": Omit<PulumiApiDocFilterableNav, keyof PulumiApiDocFilterableNavAttributes> & { [K in keyof PulumiApiDocFilterableNav & keyof PulumiApiDocFilterableNavAttributes]?: PulumiApiDocFilterableNav[K] } & { [K in keyof PulumiApiDocFilterableNav & keyof PulumiApiDocFilterableNavAttributes as `attr:${K}`]?: PulumiApiDocFilterableNavAttributes[K] } & { [K in keyof PulumiApiDocFilterableNav & keyof PulumiApiDocFilterableNavAttributes as `prop:${K}`]?: PulumiApiDocFilterableNav[K] };
        "pulumi-api-doc-nav-node": Omit<PulumiApiDocNavNode, keyof PulumiApiDocNavNodeAttributes> & { [K in keyof PulumiApiDocNavNode & keyof PulumiApiDocNavNodeAttributes]?: PulumiApiDocNavNode[K] } & { [K in keyof PulumiApiDocNavNode & keyof PulumiApiDocNavNodeAttributes as `attr:${K}`]?: PulumiApiDocNavNodeAttributes[K] } & { [K in keyof PulumiApiDocNavNode & keyof PulumiApiDocNavNodeAttributes as `prop:${K}`]?: PulumiApiDocNavNode[K] };
        "pulumi-api-doc-nav-tree": Omit<PulumiApiDocNavTree, keyof PulumiApiDocNavTreeAttributes> & { [K in keyof PulumiApiDocNavTree & keyof PulumiApiDocNavTreeAttributes]?: PulumiApiDocNavTree[K] } & { [K in keyof PulumiApiDocNavTree & keyof PulumiApiDocNavTreeAttributes as `attr:${K}`]?: PulumiApiDocNavTreeAttributes[K] } & { [K in keyof PulumiApiDocNavTree & keyof PulumiApiDocNavTreeAttributes as `prop:${K}`]?: PulumiApiDocNavTree[K] };
        "pulumi-choosable": Omit<PulumiChoosable, keyof PulumiChoosableAttributes> & { [K in keyof PulumiChoosable & keyof PulumiChoosableAttributes]?: PulumiChoosable[K] } & { [K in keyof PulumiChoosable & keyof PulumiChoosableAttributes as `attr:${K}`]?: PulumiChoosableAttributes[K] } & { [K in keyof PulumiChoosable & keyof PulumiChoosableAttributes as `prop:${K}`]?: PulumiChoosable[K] };
        "pulumi-chooser": Omit<PulumiChooser, keyof PulumiChooserAttributes> & { [K in keyof PulumiChooser & keyof PulumiChooserAttributes]?: PulumiChooser[K] } & { [K in keyof PulumiChooser & keyof PulumiChooserAttributes as `attr:${K}`]?: PulumiChooserAttributes[K] } & { [K in keyof PulumiChooser & keyof PulumiChooserAttributes as `prop:${K}`]?: PulumiChooser[K] };
        "pulumi-contact-us-form": Omit<PulumiContactUsForm, keyof PulumiContactUsFormAttributes> & { [K in keyof PulumiContactUsForm & keyof PulumiContactUsFormAttributes]?: PulumiContactUsForm[K] } & { [K in keyof PulumiContactUsForm & keyof PulumiContactUsFormAttributes as `attr:${K}`]?: PulumiContactUsFormAttributes[K] } & { [K in keyof PulumiContactUsForm & keyof PulumiContactUsFormAttributes as `prop:${K}`]?: PulumiContactUsForm[K] };
        "pulumi-convert": Omit<PulumiConvert, keyof PulumiConvertAttributes> & { [K in keyof PulumiConvert & keyof PulumiConvertAttributes]?: PulumiConvert[K] } & { [K in keyof PulumiConvert & keyof PulumiConvertAttributes as `attr:${K}`]?: PulumiConvertAttributes[K] } & { [K in keyof PulumiConvert & keyof PulumiConvertAttributes as `prop:${K}`]?: PulumiConvert[K] };
        "pulumi-example": PulumiExample;
        "pulumi-examples": PulumiExamples;
        "pulumi-filter-select": PulumiFilterSelect;
        "pulumi-filter-select-option": Omit<PulumiFilterSelectOption, keyof PulumiFilterSelectOptionAttributes> & { [K in keyof PulumiFilterSelectOption & keyof PulumiFilterSelectOptionAttributes]?: PulumiFilterSelectOption[K] } & { [K in keyof PulumiFilterSelectOption & keyof PulumiFilterSelectOptionAttributes as `attr:${K}`]?: PulumiFilterSelectOptionAttributes[K] } & { [K in keyof PulumiFilterSelectOption & keyof PulumiFilterSelectOptionAttributes as `prop:${K}`]?: PulumiFilterSelectOption[K] };
        "pulumi-filter-select-option-group": Omit<PulumiFilterSelectOptionGroup, keyof PulumiFilterSelectOptionGroupAttributes> & { [K in keyof PulumiFilterSelectOptionGroup & keyof PulumiFilterSelectOptionGroupAttributes]?: PulumiFilterSelectOptionGroup[K] } & { [K in keyof PulumiFilterSelectOptionGroup & keyof PulumiFilterSelectOptionGroupAttributes as `attr:${K}`]?: PulumiFilterSelectOptionGroupAttributes[K] } & { [K in keyof PulumiFilterSelectOptionGroup & keyof PulumiFilterSelectOptionGroupAttributes as `prop:${K}`]?: PulumiFilterSelectOptionGroup[K] };
        "pulumi-hubspot-form": Omit<PulumiHubspotForm, keyof PulumiHubspotFormAttributes> & { [K in keyof PulumiHubspotForm & keyof PulumiHubspotFormAttributes]?: PulumiHubspotForm[K] } & { [K in keyof PulumiHubspotForm & keyof PulumiHubspotFormAttributes as `attr:${K}`]?: PulumiHubspotFormAttributes[K] } & { [K in keyof PulumiHubspotForm & keyof PulumiHubspotFormAttributes as `prop:${K}`]?: PulumiHubspotForm[K] };
        "pulumi-multi-select-form": Omit<PulumiMultiSelectForm, keyof PulumiMultiSelectFormAttributes> & { [K in keyof PulumiMultiSelectForm & keyof PulumiMultiSelectFormAttributes]?: PulumiMultiSelectForm[K] } & { [K in keyof PulumiMultiSelectForm & keyof PulumiMultiSelectFormAttributes as `attr:${K}`]?: PulumiMultiSelectFormAttributes[K] } & { [K in keyof PulumiMultiSelectForm & keyof PulumiMultiSelectFormAttributes as `prop:${K}`]?: PulumiMultiSelectForm[K] };
        "pulumi-registry-list-search": PulumiRegistryListSearch;
        "pulumi-resource-links": Omit<PulumiResourceLinks, keyof PulumiResourceLinksAttributes> & { [K in keyof PulumiResourceLinks & keyof PulumiResourceLinksAttributes]?: PulumiResourceLinks[K] } & { [K in keyof PulumiResourceLinks & keyof PulumiResourceLinksAttributes as `attr:${K}`]?: PulumiResourceLinksAttributes[K] } & { [K in keyof PulumiResourceLinks & keyof PulumiResourceLinksAttributes as `prop:${K}`]?: PulumiResourceLinks[K] };
        "pulumi-root": PulumiRoot;
        "pulumi-tooltip": PulumiTooltip;
        "pulumi-top-button": PulumiTopButton;
        "pulumi-user-toggle": Omit<PulumiUserToggle, keyof PulumiUserToggleAttributes> & { [K in keyof PulumiUserToggle & keyof PulumiUserToggleAttributes]?: PulumiUserToggle[K] } & { [K in keyof PulumiUserToggle & keyof PulumiUserToggleAttributes as `attr:${K}`]?: PulumiUserToggleAttributes[K] } & { [K in keyof PulumiUserToggle & keyof PulumiUserToggleAttributes as `prop:${K}`]?: PulumiUserToggle[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pulumi-api-doc-filterable-nav": LocalJSX.IntrinsicElements["pulumi-api-doc-filterable-nav"] & JSXBase.HTMLAttributes<HTMLPulumiApiDocFilterableNavElement>;
            "pulumi-api-doc-nav-node": LocalJSX.IntrinsicElements["pulumi-api-doc-nav-node"] & JSXBase.HTMLAttributes<HTMLPulumiApiDocNavNodeElement>;
            "pulumi-api-doc-nav-tree": LocalJSX.IntrinsicElements["pulumi-api-doc-nav-tree"] & JSXBase.HTMLAttributes<HTMLPulumiApiDocNavTreeElement>;
            /**
             * The Choosable component is useful for showing or hiding information based on the
             * currently selected ChooserType and value. For example, a component defined as:
             *     <pulumi-choosable type="language" value="typescript">
             *         I <3 TypeScript.
             *     </pulumi-choosable>
             * ...would display "I <3 TypeScript" only when the user's currently (or most recently)
             * selected language choice is TypeScript.
             */
            "pulumi-choosable": LocalJSX.IntrinsicElements["pulumi-choosable"] & JSXBase.HTMLAttributes<HTMLPulumiChoosableElement>;
            /**
             * The Chooser component renders a set of selectable tabs based on the type and options
             * properties provided. For example, this definition:
             *     <pulumi-chooser type="language" value="typescript,python,go"></pulumi-chooser>
             * ...would render three tabs. Clicking a tab dispatches an action that sets the
             * associated value on the store, allowing any pulumi-choosable component on the page to
             * be shown or hidden automatically.
             * Alternatively, you can provide one or more pulumi-choosable components as children of
             * this component, which will have the effect of treating them as tabbed content,
             * irrespective of what may or may not be set on the global store. For example:
             *     <pulumi-chooser type="language" value="typescript,javascript">
             *         <pulumi choosable type="language" value="typescript">Some TypeScript</pulumi-choosable>
             *         <pulumi choosable type="language" value="javascript">Some JavaScript</pulumi-choosable>
             *     </pulumi-chooser>
             */
            "pulumi-chooser": LocalJSX.IntrinsicElements["pulumi-chooser"] & JSXBase.HTMLAttributes<HTMLPulumiChooserElement>;
            "pulumi-contact-us-form": LocalJSX.IntrinsicElements["pulumi-contact-us-form"] & JSXBase.HTMLAttributes<HTMLPulumiContactUsFormElement>;
            "pulumi-convert": LocalJSX.IntrinsicElements["pulumi-convert"] & JSXBase.HTMLAttributes<HTMLPulumiConvertElement>;
            "pulumi-example": LocalJSX.IntrinsicElements["pulumi-example"] & JSXBase.HTMLAttributes<HTMLPulumiExampleElement>;
            "pulumi-examples": LocalJSX.IntrinsicElements["pulumi-examples"] & JSXBase.HTMLAttributes<HTMLPulumiExamplesElement>;
            "pulumi-filter-select": LocalJSX.IntrinsicElements["pulumi-filter-select"] & JSXBase.HTMLAttributes<HTMLPulumiFilterSelectElement>;
            "pulumi-filter-select-option": LocalJSX.IntrinsicElements["pulumi-filter-select-option"] & JSXBase.HTMLAttributes<HTMLPulumiFilterSelectOptionElement>;
            "pulumi-filter-select-option-group": LocalJSX.IntrinsicElements["pulumi-filter-select-option-group"] & JSXBase.HTMLAttributes<HTMLPulumiFilterSelectOptionGroupElement>;
            "pulumi-hubspot-form": LocalJSX.IntrinsicElements["pulumi-hubspot-form"] & JSXBase.HTMLAttributes<HTMLPulumiHubspotFormElement>;
            "pulumi-multi-select-form": LocalJSX.IntrinsicElements["pulumi-multi-select-form"] & JSXBase.HTMLAttributes<HTMLPulumiMultiSelectFormElement>;
            "pulumi-registry-list-search": LocalJSX.IntrinsicElements["pulumi-registry-list-search"] & JSXBase.HTMLAttributes<HTMLPulumiRegistryListSearchElement>;
            "pulumi-resource-links": LocalJSX.IntrinsicElements["pulumi-resource-links"] & JSXBase.HTMLAttributes<HTMLPulumiResourceLinksElement>;
            "pulumi-root": LocalJSX.IntrinsicElements["pulumi-root"] & JSXBase.HTMLAttributes<HTMLPulumiRootElement>;
            /**
             * The ToolTip component shows a tooltip bubble above another element when you hover over
             * (or, on mobile tap on) it. Use the named `content` slot for supplying the markup to
             * show in the bubble.
             * Usage:
             * <pulumi-tooltip>
             *     <i class="fas fa-question-circle"></i>
             *     <span slot="content">
             *         You hovered over (or tapped on) the thing!
             *     </span>
             * </pulumi-tooltip>
             */
            "pulumi-tooltip": LocalJSX.IntrinsicElements["pulumi-tooltip"] & JSXBase.HTMLAttributes<HTMLPulumiTooltipElement>;
            "pulumi-top-button": LocalJSX.IntrinsicElements["pulumi-top-button"] & JSXBase.HTMLAttributes<HTMLPulumiTopButtonElement>;
            "pulumi-user-toggle": LocalJSX.IntrinsicElements["pulumi-user-toggle"] & JSXBase.HTMLAttributes<HTMLPulumiUserToggleElement>;
        }
    }
}
