// Copyright 2024, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package docs

import (
	"regexp"
	"strings"
)

// sanitizeDescription cleans up common markdown issues found in upstream
// provider schema descriptions (typically from Terraform-bridged providers).
//
// Some upstream providers use non-standard markdown patterns that render
// correctly in the Terraform Registry but break under goldmark (CommonMark).
// This function normalizes those patterns before doc generation.
func sanitizeDescription(s string) string {
	s = stripLangSpans(s)
	s = stripTerraformArgSections(s)
	s = fixHTMLBullets(s)
	s = fixTableSeparators(s)
	return s
}

// langSpanRegex matches <span pulumi-lang-*="...">text</span> elements.
//
// These spans are generated by the Pulumi SDK's schema renderer to provide
// language-specific names (e.g., containerId vs container_id). However, no
// frontend code in the registry processes these attributes — they're dead
// markup that bloats the HTML and confuses the markdown parser when embedded
// in blockquotes, list items, and inline text.
//
// We strip the span wrapper and keep only the text content.
var langSpanRegex = regexp.MustCompile(
	`<span\s+[^>]*pulumi-lang-[^>]*>([^<]*)</span>`,
)

func stripLangSpans(s string) string {
	return langSpanRegex.ReplaceAllString(s, "$1")
}

// stripTerraformArgSections removes "## Argument Reference" and "## Attributes
// Reference" sections from descriptions. Some Terraform-bridged providers embed
// these Terraform-style documentation sections in the resource description,
// duplicating the structured Pulumi API docs that are generated separately.
// They render poorly in the registry and add hundreds of lines of redundant content.
var tfSectionRegex = regexp.MustCompile(
	`(?m)^## (?:Argument|Attributes?) Reference[^\n]*\n(?:[\s\S]*?)(?:\n## |\z)`,
)

func stripTerraformArgSections(s string) string {
	// We need to be careful not to eat the next ## heading.
	// Find each section and remove everything up to (but not including) the next ## heading.
	for {
		loc := tfSectionRegex.FindStringIndex(s)
		if loc == nil {
			break
		}
		end := loc[1]
		// If the match ends with "\n## ", keep the "\n## " for the next section.
		if end > 3 && s[end-4:end] == "\n## " {
			end -= 4
		}
		s = s[:loc[0]] + s[end:]
	}
	return s
}

// fixHTMLBullets converts <br> &#8226; patterns to proper markdown list items.
//
// Some Terraform providers use raw HTML bullets inside blockquotes:
//
//	> **IMPORTANT:**
//	<br> &#8226; First item
//	<br> &#8226; Second item
//
// The <br> lines lack the > prefix, so they break out of the blockquote in
// goldmark. Converting to markdown list items produces clean rendering:
//
//	> **IMPORTANT:**
//
//	- First item
//	- Second item
func fixHTMLBullets(s string) string {
	// Handle all spacing variations between <br>, &#8226;, and trailing space.
	for _, pattern := range []string{
		"<br> &#8226; ",
		"<br>&#8226; ",
		"<br> &#8226;",
		"<br>&#8226;",
	} {
		s = strings.ReplaceAll(s, pattern, "\n- ")
	}
	return s
}

// fixTableSeparators normalizes markdown table separator rows that have
// trailing whitespace inside cells. goldmark (CommonMark) doesn't recognize
// these as valid tables.
//
// Before:
//
//	| Col A     | Col B       |
//	|:------     |:------      |
//
// After:
//
//	| Col A     | Col B       |
//	|:------|:------|
func fixTableSeparators(s string) string {
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if isTableSeparatorRow(trimmed) {
			lines[i] = normalizeTableSeparatorRow(trimmed)
		}
	}
	return strings.Join(lines, "\n")
}

// isTableSeparatorRow returns true if the line looks like a markdown table
// separator row, e.g. "|:---|:---|" or "| --- | --- |".
func isTableSeparatorRow(line string) bool {
	if len(line) < 3 {
		return false
	}
	if line[0] != '|' || line[len(line)-1] != '|' {
		return false
	}

	// Split into cells (skip empty strings from leading/trailing |).
	cells := strings.Split(line[1:len(line)-1], "|")
	if len(cells) == 0 {
		return false
	}

	for _, cell := range cells {
		cell = strings.TrimSpace(cell)
		if cell == "" {
			// Empty cell between || is not a valid separator.
			return false
		}
		if !isValidSeparatorCell(cell) {
			return false
		}
	}
	return true
}

// isValidSeparatorCell returns true if the cell content is a valid table
// separator: optional leading colon, one or more dashes, optional trailing
// colon (e.g., "---", ":---", "---:", ":---:").
func isValidSeparatorCell(cell string) bool {
	hasDash := false
	for i, ch := range cell {
		switch ch {
		case ':':
			// Colons are only valid at the start or end.
			if i != 0 && i != len(cell)-1 {
				return false
			}
		case '-':
			hasDash = true
		default:
			return false
		}
	}
	return hasDash
}

// normalizeTableSeparatorRow strips internal whitespace from each cell in a
// table separator row so goldmark can parse it.
func normalizeTableSeparatorRow(line string) string {
	cells := strings.Split(line[1:len(line)-1], "|")
	normalized := make([]string, len(cells))
	for i, cell := range cells {
		normalized[i] = strings.TrimSpace(cell)
	}
	return "|" + strings.Join(normalized, "|") + "|"
}
