name: "Check Go"

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
        description: |
          The file path from the root of the repo to the go code to check. For example:

          	tools/resourcedocsgen/
jobs:
  prerequisites:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
         sparse-checkout: |
           ${{ inputs.path }}
           .golangci.yml
    - name: Setup Go
      uses: actions/setup-go@v5
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.61
        working-directory: ${{ inputs.path }}
        args: --config $GITHUB_WORKSPACE/.golangci.yml
