name: "Scheduled jobs: Run browser tests"
on:
  schedule:
    # Run every day at 2:00PM UTC.
    - cron: "0 14 * * *"
  workflow_dispatch:
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  all:
    env:
      GOPATH: ${{ github.workspace }}/go
    name: Run browser tests
    runs-on: pulumi-ubuntu-8core
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::388588623842:role/ContinuousDelivery
          role-session-name: docs-deploy
          role-duration-seconds: 7200
          aws-region: us-west-2

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.135.0"
          extended: true

      - name: Run browser tests
        run: make run-browser-tests
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
