permissions: write-all # Equivalent to default permissions plus id-token: write
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false
name: "Scheduled jobs: Update How To Guides from examples repo"
on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch: null
jobs:
  merge:
    name: Update tutorials
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@cf5b30703ffd5ad60cc3a880c09b3a9592b9372d # v1
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}

      - name: Checkout examples repo
        id: checkout-examples
        uses: actions/checkout@v4
        with:
          repository: pulumi/examples
          token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
          path: "examples"

      - name: Run mktutorial
        run: |
          ./scripts/ci/mktutorial.sh $GITHUB_WORKSPACE/examples

      - name: Create a pull request
        id: ensure-pr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: tutorials/refresh
          author: Pulumi Bot <bot@pulumi.com>
          committer: Pulumi Bot <bot@pulumi.com>
          title: Update tutorials
          commit-message: "Update tutorials from ${{ steps.checkout-examples.outputs.commit }}"
          token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
          delete-branch: true
          body: |
            Regenerate all tutorials based on the latest available content at https://github.com/pulumi/examples.
      - name: Auto-merge PR
        # If the pull request was created, then we need to mark it as auto-merge.
        if: ${{ steps.ensure-pr.outputs.pull-request-operation == 'created' }}
        run: gh pr merge --auto --rebase "${{ steps.ensure-pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
  notify:
    if: failure()
    name: Send slack notification
    runs-on: ubuntu-latest
    needs: [merge]
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@cf5b30703ffd5ad60cc3a880c09b3a9592b9372d # v1
      - name: Slack Notification
        uses: docker://sholung/action-slack-notify:v2.3.0
        env:
          SLACK_CHANNEL: registry-ops
          SLACK_COLOR: "#F54242"
          SLACK_MESSAGE: "update tutorials failure in pulumi/docs repo :meow_sad:"
          SLACK_USERNAME: docsbot
          SLACK_WEBHOOK: ${{ steps.esc-secrets.outputs.SLACK_WEBHOOK_URL }}
          SLACK_ICON: https://www.pulumi.com/logos/brand/avatar-on-white.png
